
print("Hello, what is your name?")
name = input()
print(f"Hi {(name.capitalize())}! It is great to meet you! May I ask how old are you?")
age = input()
print(f"{age}? Wow! So young!")
print("So, what would you DOB be?")
DOB = input()
print("And how about your height?")
height = input()
print("That is a great height!")
print(f"So, {(name.capitalize())}, you are {age} years old, so, born in {DOB}, and you are {height}! That is amazing!")
print("Now, I will need to register your address. What is your house/flat name and number?")
house_number = input()
print("Ok. Now, what is your street name and number?")
street_details = input()
print("And lastly, what is your postcode?")
postcode = input()
print(f"Amazing! So, your address is {house_number}, on {street_details}, with the postcode {postcode}.")
print("I am also curious about some of your hobbies, if you could please share that with me?")
hobbies = input()
print(f"Wow! You enjoy {hobbies}! You sound like a very interesting person!")
print(f"It has been great meeting you, {(name.captalize())}!")
