
print("Hello, what is your name?")
name = input()
print(f"Hi {name}! It is great to meet you! May I ask how old are you?")
# print(name)
# print("How old are you?")
age = input()
print(f"{age}? Wow! So young!")
print("So, what would you DOB be?")
answer = input()
print(f"Great! Now, just to confirm that {answer} is your DOB?")
DOB_confirm = input(1/0)
print("amazing! Thank you!")